### PR TITLE
[skip vbump] v1.0.0

### PR DESCRIPTION
**Pull request by pawelru**

### CODE REVIEW

**Comment by pawelru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pawelru** [comment]
Submitted

**Comment by pawelru** [comment]
resubmitted

**Comment by pawelru** [comment]
on cran: https://cran.r-project.org/web/packages/roxy.shinylive/index.html

**Review by averissimo — APPROVED** [review]
:+1: 

Suggested some optional changes.. feel free to merge without them:

- Change for a smoother sentence
- Adding newlines after each full stop (markdown will keep the phrase in the same line and it's easier to maintain)

**Pull request merged**
