### PR TITLE
Make sure that the examples take up the full page width

### LINKED ISSUE #5: [Question]: How to properly add examples so shinylive works properly?
### What is your question?

Based on the readme I tried the following steps:
1. Installed the `roxy.shinylive`
2. Edited the `DESCRIPTION` file with `roxygen: list(markdown = TRUE, packages = c("roxy.shinylive"))`
3. In one of the examples ([example_module](https://insightsengineering.github.io/teal/latest-tag/reference/example_module.html)), I included the `@examplesShinylive ` tag.
4. ~Of course I had to run the docs via a static server to make it work so I did that using `httpuv::runStaticServer(dir = "/Users/vedha/insightsengineering/teal/docs/")`. Would be nice to mention this in the docs so people don't get confused when they don't see this working when opening the static HTML file like they're used to.~ I see that this is just an iframe embed so there is no need to serve it.

This had a few small issues with how the examples were written and to make it work I had to make sure that:
1. The `library(teal)` was called in the example. Should we have a hook to call the package before running any example?
2. Since the `shinyApp()` was run inside the `if (interactive())` it did not work unless I changed the if condition to something like this `interactive() || !is.null(getOption('webr_pkg_repos'))` (not recommending this, I was just testing)
3. The [iframe width of `140%`](https://github.com/insightsengineering/roxy.shinylive/blob/4c631d574b8ca5ee8a14176fc9b9f9038c8347a9/R/tag_examplesShinylive.R#L209) seems to overlap and cause layout issues for me. I don't understand why we have this.
4. It would be nice if we display the shinylive app below the example code.

The final example roxygen code looked like this in my case:
```r
#' @inheritParams teal_modules
#' @return A `teal` module which can be included in the `modules` argument to [init()].
#' @examplesShinylive
#' @examples
#' 
#' library(teal)
#' app <- init(
#'   data = teal_data(IRIS = iris, MTCARS = mtcars),
#'   modules = example_module()
#' )
#' if (interactive() || !is.null(getOption('webr_pkg_repos'))) {
#'   shinyApp(app$ui, app$server)
#' }
#' @export
```

So, I'm looking for a better way to write examples, or add supporting hooks to make it easier to use this package.

Screenshot 2024-09-23 at 3 52 54 PM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### PR DESCRIPTION
**Pull request by vedhav**
Closes #5 
Here is a screenshot of the reference page with multiple examples.

screencapture-file-Users-vedha-insightsengineering-teal-modules-general-docs-reference-tm-g-response-html-2024-11-04-20_19_17

### CODE REVIEW

**Comment by pawelru** [comment]
Is this what we expect?
- pkgdown
image
- manual in webbrowser
image

**Comment by vedhav** [comment]
I see you have a wider monitor screen. I think the optimal thing here would be to set a maximum width that looks good. Which is generally a 16:8 aspect ratio and given that we have an `800px` height the max width can be `1400px`. Let me make this change.

**Comment by vedhav** [comment]
How about now? It is centered with a max-width. But it will still have the window's width as the normal width to feel responsive when width is reduced.
screencapture-file-D-insightsengineering-teal-modules-general-docs-reference-tm-data-table-html-2024-11-05-22_04_35

**Comment by pawelru** [comment]
This one is great. Thank you!

image

**Comment by vedhav** [comment]
haha we both posted at the exact same time!

**Comment by pawelru** [comment]
I am happy with the outcome. Please just have a look at the R CMD CHECK results - tidy HTML is failing. This is because tidy will be used on the package that uses `roxy.shinylive` and create R CMD NOTE. So we need to care about this in here.

**Comment by vedhav** [comment]
@pawelru I remember we discussed moving the shinylive examples below the shiny examples code. I tried to make this happen but couldn’t figure it out I'd differ on your roxygen black magic skills.

**Comment by pawelru** [comment]
copy&paste from slack if one will be looking into this

> The order is hardcoded in pkgdown [here](https://github.com/r-lib/pkgdown/blob/8d9cba19fe597bba170f8d4c99f351491ab4f4d1/inst/BS5/templates/content-reference-topic.html#L27-L41). roxy.shinylive creates a section and every section is before examples. pkgdown API is not very open to provide your own template. And even if it is - it would go beyond the aimed complexity of roxy.shinylive . I'm afraid that we need to live with this...

> Yes, we can provide a custom template as a file in the repo ([reference](https://pkgdown.r-lib.org/articles/customise.html?q=template#template-packages:~:text=Templates%20in%20inst/pkgdown/templates/%20will%20override%20the%20default%20templates)). This way we can render #sections  then #examples  and then our custom #xyz .
The problem then is how to make our stuff to be stored as a custom xyz . This goes probably beyond pkgdown into roxygen2. Currently, roxygen2 can only be "extended" with a custom section ([manual](https://cran.r-project.org/web/packages/roxygen2/vignettes/extending.html)).
This looks to me that the template only allows for custom html tweaks (incl. css and js) but not necessarily adding a new element (on the level of existing section).
Regardless - the whole idea was to have a small extension that is easily implementable. This whole thing would require additional files and that's a complexity that I would like to avoid.

> [Here](https://github.com/r-lib/pkgdown/blob/main/R/build-reference.R#L328-L392) is the piece of code that creates an object which is resolved against that template I shared earlier. The returned object is created from scratch and it has a fixed structure - it does not allow to create a new xyz element that could be potentially resolved using #xyz in the template.
This function also hardcodes the order of the sections - [here](https://github.com/r-lib/pkgdown/blob/main/R/build-reference.R#L381-L384) - in particular: not the template. roxygen2 only allows (or instructs) how to write into the section element of this. As we can see it's going to be rendered between seealso and author.

**Review by pawelru — APPROVED** [review]
Thank you!

**Comment by pawelru** [comment]
Now we are expecting that PRs to both tmg and tmc will re-generate the docs using this new version of `roxy.shinylive` and we are expecting some changes in the .Rd files.

**Pull request merged**
